Create database day3

SElect LEN('jshjdhwe');

/* concatenation in two ways */
SELECT CONCAT('HELLO', ' ', 'WORLD');
SELECT 'HELLO'+' '+'WORLD';

/*SHOWING CURRENT DATE AN TIME*/
SELECT GETDATE();

/*SHOWING THE PART OF THE DATE IN DIFFERENT SEGMENTS*/
SELECT DATEPART(YEAR, GETDATE())
SELECT DATEPART(MONTH, GETDATE())
SELECT DATEPART(DAY, GETDATE())
SELECT DATEPART(HOUR, GETDATE())
SELECT DATEPART(MINUTE, GETDATE())
SELECT DATEPART(SECOND, GETDATE())
SELECT DATEPART(YEAR, '2019-07-05')


/*SHOWING THE PART OF THE DATE IN ONE LINE*/
SELECT 
DATEPART(YEAR, GETDATE()),
DATEPART (MONTH, GETDATE()),
DATEPART(DAY, GETDATE()),
DATEPART(HOUR, GETDATE()),
DATEPART(MINUTE, GETDATE()),
DATEPART(SECOND, GETDATE()),
DATEPART(YEAR, '2019-07-05');


/*SHOWING NOW AND THE PART OF THE DATE IN ONE LINE WITH THE TITLE*/
SELECT GETDATE() AS [NOW];

SELECT GETDATE() AS [MY_NOW],
DATEPART(YEAR, GETDATE()) AS [MY_YEAR],
DATEPART (MONTH, GETDATE()) AS [MY_MONTH],
DATEPART(DAY, GETDATE()) AS [MY_DAY],
DATEPART(HOUR, GETDATE()) AS [MY_HOUR],
DATEPART(MINUTE, GETDATE()) AS [MY_MIN],
DATEPART(SECOND, GETDATE()) AS [MY_SEC],
DATEPART(MILLISECOND, GETDATE()) AS [MY_MSEC];




